# [MacroF1]: Mean 93.99 Std 0.92
# [MicroF1]: Mean 94.09 Std 0.92
seed: 82
repeat: 3
dataset:
  name: acm
  tgt_type: paper
  split: random
optim:
  epochs: 100
  lr: 7.5e-4
  wd: 2.5e-6
  warmup: 20
model:
  mp_hop: 4
  lp_hop: 3
  hidden_dim: 256
  dropout: 0.5
  input_dropout: 0.5
  attention_dropout: 0.0
  num_attention_heads: 1
  n_fp_layers: 2
  residual: True
  label_prop: True
  selective: False
  task:
    layers: 2
  l2_norm: True