repeat: 3
seed: 42
dataset:
  name: actor
  tgt_type: starring
  split: random
optim:
  epochs: 100
  lr: 5e-3
  wd: 5e-6
  eval_protocol: 'loss'
model:
  mp_hop: 2
  lp_hop: 2
  hidden_dim: 256
  dropout: 0.0
  input_dropout: 0.5
  attention_dropout: 0.0
  num_attention_heads: 1
  n_fp_layers: 3
  residual: True
  label_prop: True
  selective: False
  task:
    layers: 2
  l2_norm: True
  alpha: 0.25
 